### ISSUE TITLE
Peer-to-peer code review February 3rd 2023

### ISSUE THREAD

**Issue by Chaseknis** [Thoth1111/Leaderboard#3]
# Hello @Thoth1111 ✋🏼 

## Great Job 🥇 

- No linter Errors ✅ 
- Installed webpack ✅ 
- API working fine ✅  

<img src="https://media2.giphy.com/media/ldtheoBzkN1jtyLx2V/giphy.gif"/>

## Changes Required ♻️ 

- I would suggest that you document your work professionally by Updating your README.md file to make it easier for users to understand your work

## _Optional Comments_

- It would be better to order your scores from the best score to the last score to make the output more organized.

**Comment by Thoth1111** [comment]
Thank you for the feedback. These issues have all been addressed in my most recent pull request (#4).
