### ISSUE TITLE
Semantics and Documentation - P2P Review

### ISSUE THREAD

**Issue by cindykandie** [Thoth1111/Leaderboard#5]
Hey @Thoth1111 
🌸  You achieved to write really good code and create a greater project with a beautiful UI
**You could make it better by:**
- Using semantically correct tags such as main instead of the generic div
- Professionally edit your ReadMe to ensure visitors and future contributing developers have an easy time navigating your project and understanding it

**Comment by Thoth1111** [comment]
Thank you for the review.
